### PR TITLE
feat: Treat more files as ref, glob dot files

### PR DESCRIPTION
**Pull request by dstoc**

### CODE REVIEW

**Comment by tbuckley** [comment]
Will this mess up PromptFormatter, causing it to recognize all misc files as images? Before, unrecognized file extensions would just end up passed through as the file uri string.

https://github.com/tbuckley/evals-pwa/blob/main/src%2Flib%2Futils%2FHandlebarsPromptFormatter.ts#L32

**Comment by dstoc** [comment]
> Will this mess up PromptFormatter, causing it to recognize all misc files as images?

I see, yes I think so. Maybe we should add an ImageReference to be able to distinguish there.

**Comment by tbuckley** [comment]
Or could just switch the file extension check to there. Use the uri if not an image to keep the current behavior; or fallback of reading unknown files as utf-8

**Comment by dstoc** [comment]
Added a `type` field to FileReference, should be useful on the JS side since instanceof won't work there.

Also changed assertions to pass the FileReference directly.

**Pull request merged**
